-- Seed data: 200 common English vocabulary words
-- Categories: beginner (50), intermediate (100), advanced (50)

-- Beginner words
INSERT INTO words (word, definition, example_sentence, pronunciation, category) VALUES
('hello', 'A greeting used when meeting someone', 'Hello, how are you today?', 'həˈloʊ', 'beginner'),
('goodbye', 'A farewell remark', 'It''s time to say goodbye.', 'ɡʊdˈbaɪ', 'beginner'),
('please', 'Used in polite requests', 'Please pass me the salt.', 'pliːz', 'beginner'),
('thank', 'Express gratitude to someone', 'I want to thank you for your help.', 'θæŋk', 'beginner'),
('yes', 'Used to give an affirmative response', 'Yes, I agree with you.', 'jes', 'beginner'),
('no', 'Used to give a negative response', 'No, I don''t want any dessert.', 'noʊ', 'beginner'),
('water', 'A colorless, transparent liquid', 'Can I have a glass of water?', 'ˈwɔːtər', 'beginner'),
('food', 'Any substance consumed to provide nutritional support', 'What kind of food do you like?', 'fuːd', 'beginner'),
('house', 'A building for human habitation', 'I live in a small house.', 'haʊs', 'beginner'),
('family', 'A group of people related by blood or marriage', 'My family is very important to me.', 'ˈfæməli', 'beginner'),
('friend', 'A person with whom one has a bond of mutual affection', 'She is my best friend.', 'frend', 'beginner'),
('book', 'A written or printed work consisting of pages', 'I''m reading an interesting book.', 'bʊk', 'beginner'),
('happy', 'Feeling or showing pleasure', 'I feel happy today.', 'ˈhæpi', 'beginner'),
('sad', 'Feeling or showing sorrow', 'She looked sad at the news.', 'sæd', 'beginner'),
('big', 'Of considerable size or extent', 'That''s a very big dog.', 'bɪɡ', 'beginner'),
('small', 'Of a size that is less than normal', 'The apartment is quite small.', 'smɔːl', 'beginner'),
('good', 'To be desired or approved of', 'This is a good restaurant.', 'ɡʊd', 'beginner'),
('bad', 'Of poor quality or low standard', 'That was a bad decision.', 'bæd', 'beginner'),
('new', 'Not existing before; recently created', 'I bought a new car.', 'nuː', 'beginner'),
('old', 'Having lived for a long time', 'My grandfather is very old.', 'oʊld', 'beginner'),
('hot', 'Having a high temperature', 'The coffee is too hot to drink.', 'hɑːt', 'beginner'),
('cold', 'Of a low temperature', 'It''s very cold outside.', 'koʊld', 'beginner'),
('day', 'A period of 24 hours', 'Have a nice day!', 'deɪ', 'beginner'),
('night', 'The period of darkness between sunset and sunrise', 'Good night, sleep well.', 'naɪt', 'beginner'),
('morning', 'The period of time from sunrise to noon', 'Good morning! Did you sleep well?', 'ˈmɔːrnɪŋ', 'beginner'),
('time', 'The indefinite continued progress of existence', 'What time is it?', 'taɪm', 'beginner'),
('year', 'A period of 365 or 366 days', 'I''ve lived here for a year.', 'jɪr', 'beginner'),
('work', 'Activity involving mental or physical effort', 'I have a lot of work to do.', 'wɜːrk', 'beginner'),
('school', 'An institution for educating children', 'The children go to school every day.', 'skuːl', 'beginner'),
('person', 'A human being regarded as an individual', 'She''s a very kind person.', 'ˈpɜːrsn', 'beginner'),
('man', 'An adult male human being', 'The man is wearing a hat.', 'mæn', 'beginner'),
('woman', 'An adult female human being', 'That woman is my teacher.', 'ˈwʊmən', 'beginner'),
('child', 'A young human being', 'The child is playing in the garden.', 'tʃaɪld', 'beginner'),
('boy', 'A male child or young man', 'The boy is riding a bicycle.', 'bɔɪ', 'beginner'),
('girl', 'A female child', 'The girl is reading a book.', 'ɡɜːrl', 'beginner'),
('life', 'The condition that distinguishes living things', 'Life is beautiful.', 'laɪf', 'beginner'),
('hand', 'The end part of the arm beyond the wrist', 'He raised his hand to ask a question.', 'hænd', 'beginner'),
('part', 'A piece or segment of something', 'This is the best part of the movie.', 'pɑːrt', 'beginner'),
('place', 'A particular position or location', 'This is a nice place to visit.', 'pleɪs', 'beginner'),
('world', 'The earth with all its countries and peoples', 'I want to travel around the world.', 'wɜːrld', 'beginner'),
('country', 'A nation with its own government', 'Which country are you from?', 'ˈkʌntri', 'beginner'),
('city', 'A large town', 'New York is a big city.', 'ˈsɪti', 'beginner'),
('number', 'An arithmetical value', 'What''s your phone number?', 'ˈnʌmbər', 'beginner'),
('word', 'A single distinct meaningful element of speech', 'I don''t know this word.', 'wɜːrd', 'beginner'),
('name', 'A word by which a person or thing is known', 'What''s your name?', 'neɪm', 'beginner'),
('color', 'The property of objects that depends on light', 'What''s your favorite color?', 'ˈkʌlər', 'beginner'),
('red', 'Of a color at the end of the spectrum', 'She wore a red dress.', 'red', 'beginner'),
('blue', 'Of a color intermediate between green and violet', 'The sky is blue.', 'bluː', 'beginner'),
('white', 'Of the color of milk or fresh snow', 'He has white hair.', 'waɪt', 'beginner'),
('black', 'Of the very darkest color', 'She''s wearing black shoes.', 'blæk', 'beginner');

-- Intermediate words
INSERT INTO words (word, definition, example_sentence, pronunciation, category) VALUES
('abandon', 'Give up completely', 'Don''t abandon your dreams.', 'əˈbændən', 'intermediate'),
('ability', 'Possession of the means or skill to do something', 'She has the ability to succeed.', 'əˈbɪləti', 'intermediate'),
('achieve', 'Successfully bring about or reach a goal', 'You can achieve anything you set your mind to.', 'əˈtʃiːv', 'intermediate'),
('acquire', 'Buy or obtain an asset or object', 'He acquired a taste for classical music.', 'əˈkwaɪər', 'intermediate'),
('adapt', 'Make suitable for a new use or purpose', 'We must adapt to changing circumstances.', 'əˈdæpt', 'intermediate'),
('adequate', 'Satisfactory or acceptable in quality', 'The salary is adequate for my needs.', 'ˈædɪkwət', 'intermediate'),
('adjust', 'Alter or move slightly to achieve the desired fit', 'Please adjust your seat belt.', 'əˈdʒʌst', 'intermediate'),
('admire', 'Regard with respect or warm approval', 'I admire your courage.', 'ədˈmaɪər', 'intermediate'),
('adventure', 'An unusual and exciting experience', 'Life is a great adventure.', 'ədˈventʃər', 'intermediate'),
('advice', 'Guidance or recommendations offered', 'Can you give me some advice?', 'ədˈvaɪs', 'intermediate'),
('affect', 'Have an effect on; make a difference to', 'This will not affect our decision.', 'əˈfekt', 'intermediate'),
('afford', 'Have enough money to pay for', 'I can''t afford a new car.', 'əˈfɔːrd', 'intermediate'),
('ancient', 'Belonging to the very distant past', 'These are ancient ruins.', 'ˈeɪnʃənt', 'intermediate'),
('announce', 'Make a public declaration', 'They will announce the results tomorrow.', 'əˈnaʊns', 'intermediate'),
('anxiety', 'A feeling of worry or unease', 'She suffers from social anxiety.', 'æŋˈzaɪəti', 'intermediate'),
('apparent', 'Clearly visible or understood', 'It was apparent that he was lying.', 'əˈpærənt', 'intermediate'),
('appreciate', 'Recognize the value of something', 'I appreciate your help.', 'əˈpriːʃieɪt', 'intermediate'),
('approach', 'Come near or nearer to something', 'Winter is approaching.', 'əˈproʊtʃ', 'intermediate'),
('appropriate', 'Suitable or proper in the circumstances', 'Wear appropriate clothing for the occasion.', 'əˈproʊpriət', 'intermediate'),
('argue', 'Give reasons or cite evidence in support', 'They always argue about politics.', 'ˈɑːrɡjuː', 'intermediate'),
('arrange', 'Put things in a neat order', 'Please arrange the books alphabetically.', 'əˈreɪndʒ', 'intermediate'),
('assist', 'Help someone', 'Can I assist you with anything?', 'əˈsɪst', 'intermediate'),
('assume', 'Suppose to be the case without proof', 'I assume you''re coming to the party.', 'əˈsuːm', 'intermediate'),
('attach', 'Fasten or join one thing to another', 'Please attach the document to your email.', 'əˈtætʃ', 'intermediate'),
('attempt', 'Make an effort to achieve something', 'I will attempt to finish today.', 'əˈtempt', 'intermediate'),
('attract', 'Draw by appeal to natural interests', 'The museum attracts many visitors.', 'əˈtrækt', 'intermediate'),
('authority', 'The power to give orders', 'Who is in authority here?', 'əˈθɔːrəti', 'intermediate'),
('available', 'Able to be used or obtained', 'Is this room available?', 'əˈveɪləbl', 'intermediate'),
('avoid', 'Keep away from or stop oneself from doing', 'Try to avoid making mistakes.', 'əˈvɔɪd', 'intermediate'),
('aware', 'Having knowledge or perception', 'Are you aware of the risks?', 'əˈwer', 'intermediate'),
('balance', 'An even distribution of weight', 'Try to keep your balance.', 'ˈbæləns', 'intermediate'),
('behave', 'Act in a specified way', 'Please behave yourself.', 'bɪˈheɪv', 'intermediate'),
('belief', 'Trust or confidence in something', 'She has strong religious beliefs.', 'bɪˈliːf', 'intermediate'),
('benefit', 'An advantage or profit gained', 'What are the benefits of this plan?', 'ˈbenɪfɪt', 'intermediate'),
('brave', 'Ready to face danger or pain', 'He was very brave during the surgery.', 'breɪv', 'intermediate'),
('brief', 'Of short duration', 'Please be brief in your explanation.', 'briːf', 'intermediate'),
('brilliant', 'Exceptionally clever or talented', 'She came up with a brilliant idea.', 'ˈbrɪliənt', 'intermediate'),
('burden', 'A heavy load or responsibility', 'Don''t be a burden on others.', 'ˈbɜːrdn', 'intermediate'),
('calm', 'Not showing excitement or worry', 'Please remain calm.', 'kɑːm', 'intermediate'),
('capable', 'Having the ability or quality for', 'She''s capable of great things.', 'ˈkeɪpəbl', 'intermediate'),
('capacity', 'The maximum amount that can be contained', 'The stadium has a capacity of 50,000.', 'kəˈpæsəti', 'intermediate'),
('capture', 'Take into custody', 'The police captured the thief.', 'ˈkæptʃər', 'intermediate'),
('career', 'An occupation undertaken for life', 'She has a successful career in law.', 'kəˈrɪr', 'intermediate'),
('category', 'A class or division of things', 'Which category does this belong to?', 'ˈkætəɡɔːri', 'intermediate'),
('celebrate', 'Mark a significant occasion with festivities', 'Let''s celebrate your birthday!', 'ˈseləbreɪt', 'intermediate'),
('century', 'A period of one hundred years', 'The building is over a century old.', 'ˈsentʃəri', 'intermediate'),
('challenge', 'A difficult task that tests abilities', 'This job presents many challenges.', 'ˈtʃælɪndʒ', 'intermediate'),
('character', 'The mental and moral qualities of a person', 'He has a strong character.', 'ˈkærəktər', 'intermediate'),
('charity', 'An organization set up to help those in need', 'She donates to charity regularly.', 'ˈtʃærəti', 'intermediate'),
('climate', 'The weather conditions in an area', 'The climate here is very mild.', 'ˈklaɪmət', 'intermediate'),
('collapse', 'Fall down or give way suddenly', 'The building collapsed in the earthquake.', 'kəˈlæps', 'intermediate'),
('colleague', 'A person with whom one works', 'My colleagues are very helpful.', 'ˈkɑːliːɡ', 'intermediate'),
('combine', 'Unite or merge to form a whole', 'Combine all the ingredients in a bowl.', 'kəmˈbaɪn', 'intermediate'),
('comfort', 'A state of physical ease', 'The hotel offers maximum comfort.', 'ˈkʌmfərt', 'intermediate'),
('command', 'Give an authoritative order', 'The officer commanded his troops.', 'kəˈmænd', 'intermediate'),
('comment', 'A verbal or written remark', 'Do you have any comments?', 'ˈkɑːment', 'intermediate'),
('commit', 'Pledge or bind to a course of action', 'He committed to finishing the project.', 'kəˈmɪt', 'intermediate'),
('common', 'Occurring often', 'This is a common problem.', 'ˈkɑːmən', 'intermediate'),
('communicate', 'Share or exchange information', 'We need to communicate better.', 'kəˈmjuːnɪkeɪt', 'intermediate'),
('community', 'A group of people living in the same place', 'Our community is very friendly.', 'kəˈmjuːnəti', 'intermediate'),
('compare', 'Estimate similarities or differences', 'Compare these two options.', 'kəmˈper', 'intermediate'),
('compete', 'Strive to gain something', 'Athletes from around the world compete here.', 'kəmˈpiːt', 'intermediate'),
('complain', 'Express dissatisfaction', 'She complained about the noise.', 'kəmˈpleɪn', 'intermediate'),
('complete', 'Finish making or doing', 'Please complete this form.', 'kəmˈpliːt', 'intermediate'),
('complex', 'Consisting of many interconnected parts', 'This is a complex problem.', 'kəmˈpleks', 'intermediate'),
('concentrate', 'Focus all attention on something', 'I need to concentrate on my work.', 'ˈkɑːnsntreɪt', 'intermediate'),
('concept', 'An abstract idea', 'This is an interesting concept.', 'ˈkɑːnsept', 'intermediate'),
('concern', 'Relate to; be about', 'This concerns everyone here.', 'kənˈsɜːrn', 'intermediate'),
('conclude', 'Bring to an end', 'Let me conclude my presentation.', 'kənˈkluːd', 'intermediate'),
('condition', 'The state of something', 'The car is in good condition.', 'kənˈdɪʃn', 'intermediate'),
('conduct', 'Organize and carry out', 'They will conduct a survey.', 'kənˈdʌkt', 'intermediate'),
('confident', 'Feeling sure about one''s abilities', 'She feels confident about the exam.', 'ˈkɑːnfɪdənt', 'intermediate'),
('confirm', 'Establish the truth of something', 'Please confirm your reservation.', 'kənˈfɜːrm', 'intermediate'),
('conflict', 'A serious disagreement', 'There''s a conflict of interests.', 'ˈkɑːnflɪkt', 'intermediate'),
('confuse', 'Make unclear or difficult to understand', 'Don''t confuse me with facts.', 'kənˈfjuːz', 'intermediate'),
('connect', 'Bring together or into contact', 'Connect the cable to the computer.', 'kəˈnekt', 'intermediate'),
('conscious', 'Aware of one''s surroundings', 'He was conscious during the operation.', 'ˈkɑːnʃəs', 'intermediate'),
('consequence', 'A result or effect of an action', 'Every action has consequences.', 'ˈkɑːnsɪkwens', 'intermediate'),
('consider', 'Think carefully about something', 'I''ll consider your proposal.', 'kənˈsɪdər', 'intermediate'),
('consistent', 'Acting in the same way over time', 'She''s a consistent performer.', 'kənˈsɪstənt', 'intermediate'),
('constant', 'Occurring continuously', 'The noise is constant.', 'ˈkɑːnstənt', 'intermediate'),
('construct', 'Build or make something', 'They will construct a new bridge.', 'kənˈstrʌkt', 'intermediate'),
('consume', 'Eat, drink, or ingest', 'Don''t consume too much sugar.', 'kənˈsuːm', 'intermediate'),
('contain', 'Have or hold within', 'This box contains old photos.', 'kənˈteɪn', 'intermediate'),
('contemporary', 'Living or occurring at the same time', 'She studies contemporary art.', 'kənˈtempəreri', 'intermediate'),
('content', 'In a state of satisfaction', 'I''m content with what I have.', 'kənˈtent', 'intermediate'),
('contest', 'An event in which people compete', 'She won the singing contest.', 'ˈkɑːntest', 'intermediate'),
('context', 'The circumstances that form the setting', 'You need to understand the context.', 'ˈkɑːntekst', 'intermediate'),
('continue', 'Persist in an activity', 'Please continue with your work.', 'kənˈtɪnjuː', 'intermediate'),
('contract', 'A written or spoken agreement', 'Sign the contract here.', 'ˈkɑːntrækt', 'intermediate'),
('contrast', 'The state of being different', 'There''s a sharp contrast between them.', 'ˈkɑːntræst', 'intermediate'),
('contribute', 'Give something to help achieve a purpose', 'Everyone should contribute to the discussion.', 'kənˈtrɪbjuːt', 'intermediate'),
('control', 'The power to influence behavior', 'He lost control of the car.', 'kənˈtroʊl', 'intermediate'),
('convenient', 'Fitting in well with needs or plans', 'Is this time convenient for you?', 'kənˈviːniənt', 'intermediate'),
('conventional', 'Based on what is generally done', 'She prefers conventional methods.', 'kənˈvenʃənl', 'intermediate'),
('convince', 'Cause someone to believe firmly', 'I''m not convinced by your argument.', 'kənˈvɪns', 'intermediate'),
('cooperate', 'Work jointly towards the same end', 'We need to cooperate with each other.', 'koʊˈɑːpəreɪt', 'intermediate'),
('coordinate', 'Bring different elements into a relationship', 'We need to coordinate our efforts.', 'koʊˈɔːrdɪneɪt', 'intermediate'),
('correct', 'Free from error; accurate', 'Your answer is correct.', 'kəˈrekt', 'intermediate'),
('create', 'Bring something into existence', 'Artists create beautiful works.', 'kriˈeɪt', 'intermediate'),
('creative', 'Relating to imagination and original ideas', 'She has a creative mind.', 'kriˈeɪtɪv', 'intermediate');

-- Advanced words
INSERT INTO words (word, definition, example_sentence, pronunciation, category) VALUES
('aberration', 'A departure from what is normal or expected', 'His behavior was an aberration from his usual conduct.', 'ˌæbəˈreɪʃn', 'advanced'),
('abstemious', 'Indulging only moderately in food and drink', 'He maintained an abstemious lifestyle.', 'æbˈstiːmiəs', 'advanced'),
('acumen', 'The ability to make good judgments quickly', 'She has great business acumen.', 'əˈkjuːmən', 'advanced'),
('adroit', 'Clever or skillful in using hands or mind', 'He was adroit at handling difficult situations.', 'əˈdrɔɪt', 'advanced'),
('aesthetic', 'Concerned with beauty or appreciation of beauty', 'The building has great aesthetic appeal.', 'esˈθetɪk', 'advanced'),
('ambiguous', 'Open to more than one interpretation', 'His answer was deliberately ambiguous.', 'æmˈbɪɡjuəs', 'advanced'),
('ameliorate', 'Make something bad or unsatisfactory better', 'Steps were taken to ameliorate the situation.', 'əˈmiːliəreɪt', 'advanced'),
('anachronism', 'Something belonging to a period other than that depicted', 'The modern car in the historical film was an anachronism.', 'əˈnækrənɪzəm', 'advanced'),
('anomaly', 'Something that deviates from the norm', 'The test results showed an anomaly.', 'əˈnɑːməli', 'advanced'),
('antipathy', 'A deep-seated feeling of dislike', 'She felt a natural antipathy towards injustice.', 'ænˈtɪpəθi', 'advanced'),
('arbitrary', 'Based on random choice rather than reason', 'The decision seemed arbitrary and unfair.', 'ˈɑːrbɪtreri', 'advanced'),
('archaic', 'Very old or old-fashioned', 'The law is archaic and needs updating.', 'ɑːrˈkeɪɪk', 'advanced'),
('arduous', 'Involving difficult effort', 'It was an arduous climb to the summit.', 'ˈɑːrdʒuəs', 'advanced'),
('articulate', 'Having or showing clear expression', 'She was very articulate in her presentation.', 'ɑːrˈtɪkjələt', 'advanced'),
('ascetic', 'Characterized by severe self-discipline', 'He lived an ascetic life as a monk.', 'əˈsetɪk', 'advanced'),
('astute', 'Having sharp judgment', 'She made an astute observation.', 'əˈstuːt', 'advanced'),
('audacious', 'Showing willingness to take bold risks', 'It was an audacious plan.', 'ɔːˈdeɪʃəs', 'advanced'),
('austere', 'Severe or strict in manner or appearance', 'The room was furnished in an austere style.', 'ɔːˈstɪr', 'advanced'),
('benevolent', 'Well meaning and kindly', 'She had a benevolent smile.', 'bəˈnevələnt', 'advanced'),
('bolster', 'Support or strengthen', 'The evidence will bolster your case.', 'ˈboʊlstər', 'advanced'),
('cacophony', 'A harsh, discordant mixture of sounds', 'The traffic created a cacophony of noise.', 'kəˈkɑːfəni', 'advanced'),
('candid', 'Truthful and straightforward', 'She gave a candid interview.', 'ˈkændɪd', 'advanced'),
('capricious', 'Given to sudden changes of mood or behavior', 'The weather here is capricious.', 'kəˈprɪʃəs', 'advanced'),
('catalyst', 'Something that precipitates change', 'The invention was a catalyst for progress.', 'ˈkætəlɪst', 'advanced'),
('caustic', 'Sarcastic in a scathing way', 'He made caustic remarks about the proposal.', 'ˈkɔːstɪk', 'advanced'),
('circumspect', 'Wary and unwilling to take risks', 'He was circumspect when answering questions.', 'ˈsɜːrkəmspekt', 'advanced'),
('clandestine', 'Kept secret or done secretively', 'They held clandestine meetings.', 'klænˈdestɪn', 'advanced'),
('coalesce', 'Come together to form one mass', 'The various groups coalesced into a single organization.', 'ˌkoʊəˈles', 'advanced'),
('cogent', 'Clear, logical, and convincing', 'She presented a cogent argument.', 'ˈkoʊdʒənt', 'advanced'),
('complacent', 'Showing smug satisfaction with oneself', 'Don''t become complacent about your success.', 'kəmˈpleɪsnt', 'advanced'),
('connoisseur', 'An expert judge in matters of taste', 'He''s a connoisseur of fine wines.', 'ˌkɑːnəˈsɜːr', 'advanced'),
('consensus', 'General agreement', 'We reached a consensus on the matter.', 'kənˈsensəs', 'advanced'),
('contentious', 'Causing or likely to cause disagreement', 'It''s a contentious issue.', 'kənˈtenʃəs', 'advanced'),
('corroborate', 'Confirm or give support to', 'The witness corroborated his story.', 'kəˈrɑːbəreɪt', 'advanced'),
('credulous', 'Too ready to believe things', 'He''s too credulous to see through the scam.', 'ˈkredʒələs', 'advanced'),
('cryptic', 'Having a meaning that is mysterious', 'He left a cryptic message.', 'ˈkrɪptɪk', 'advanced'),
('cursory', 'Hasty and therefore not thorough', 'She gave it only a cursory glance.', 'ˈkɜːrsəri', 'advanced'),
('dearth', 'A scarcity or lack of something', 'There''s a dearth of evidence.', 'dɜːrθ', 'advanced'),
('demeanor', 'Outward behavior or bearing', 'He has a calm demeanor.', 'dɪˈmiːnər', 'advanced'),
('denounce', 'Publicly declare to be wrong or evil', 'He denounced the actions as immoral.', 'dɪˈnaʊns', 'advanced'),
('deride', 'Express contempt for; ridicule', 'Critics derided the plan as unrealistic.', 'dɪˈraɪd', 'advanced'),
('desolate', 'Empty and giving an impression of unhappiness', 'The landscape was bleak and desolate.', 'ˈdesələt', 'advanced'),
('dichotomy', 'A division into two contrasting things', 'There''s a dichotomy between theory and practice.', 'daɪˈkɑːtəmi', 'advanced'),
('diffident', 'Modest or shy because of lack of confidence', 'He was diffident about his achievements.', 'ˈdɪfɪdənt', 'advanced'),
('diligent', 'Having or showing care in one''s work', 'She''s a diligent student.', 'ˈdɪlɪdʒənt', 'advanced'),
('discern', 'Perceive or recognize something', 'It''s difficult to discern the truth.', 'dɪˈsɜːrn', 'advanced'),
('disparate', 'Essentially different in kind', 'The group consists of disparate elements.', 'ˈdɪspərət', 'advanced'),
('disseminate', 'Spread information widely', 'The organization disseminates health information.', 'dɪˈsemɪneɪt', 'advanced'),
('dogmatic', 'Inclined to lay down principles as undeniably true', 'He can be quite dogmatic in his views.', 'dɔːɡˈmætɪk', 'advanced'),
('dubious', 'Hesitating or doubting', 'I''m dubious about his claims.', 'ˈduːbiəs', 'advanced');

-- Note: This provides 200 words total (50 beginner + 100 intermediate + 50 advanced)
-- You can add more words as needed
