-- LearnEnglish Seed Data
USE learn_english;

-- Insert sample words (100+ common English words)
INSERT INTO words (english, chinese, pronunciation, category, difficulty, example_sentence) VALUES
-- Basic Level (difficulty 1)
('hello', '你好', '/həˈloʊ/', 'greeting', 1, 'Hello, how are you today?'),
('goodbye', '再见', '/ɡʊdˈbaɪ/', 'greeting', 1, 'Goodbye, see you tomorrow!'),
('thank', '感谢', '/θæŋk/', 'common', 1, 'Thank you for your help.'),
('please', '请', '/pliːz/', 'common', 1, 'Please pass me the salt.'),
('yes', '是的', '/jes/', 'common', 1, 'Yes, I agree with you.'),
('no', '不', '/noʊ/', 'common', 1, 'No, I dont think so.'),
('water', '水', '/ˈwɔːtər/', 'food', 1, 'I need a glass of water.'),
('food', '食物', '/fuːd/', 'food', 1, 'The food here is delicious.'),
('book', '书', '/bʊk/', 'education', 1, 'I am reading a book.'),
('pen', '笔', '/pen/', 'education', 1, 'Can I borrow your pen?'),
('time', '时间', '/taɪm/', 'common', 1, 'What time is it?'),
('day', '天,日', '/deɪ/', 'common', 1, 'Have a nice day!'),
('night', '夜晚', '/naɪt/', 'common', 1, 'Good night, sleep well.'),
('morning', '早晨', '/ˈmɔːrnɪŋ/', 'common', 1, 'Good morning everyone!'),
('friend', '朋友', '/frend/', 'social', 1, 'She is my best friend.'),
('family', '家庭', '/ˈfæməli/', 'social', 1, 'I love my family.'),
('house', '房子', '/haʊs/', 'living', 1, 'They bought a new house.'),
('car', '汽车', '/kɑːr/', 'transport', 1, 'I drive a red car.'),
('phone', '电话', '/foʊn/', 'technology', 1, 'My phone is ringing.'),
('computer', '电脑', '/kəmˈpjuːtər/', 'technology', 1, 'I work on my computer.'),

-- Intermediate Level (difficulty 2)
('beautiful', '美丽的', '/ˈbjuːtɪfl/', 'adjective', 2, 'What a beautiful day!'),
('important', '重要的', '/ɪmˈpɔːrtnt/', 'adjective', 2, 'This is very important.'),
('different', '不同的', '/ˈdɪfrənt/', 'adjective', 2, 'We have different opinions.'),
('interesting', '有趣的', '/ˈɪntrəstɪŋ/', 'adjective', 2, 'That sounds interesting.'),
('difficult', '困难的', '/ˈdɪfɪkəlt/', 'adjective', 2, 'This problem is difficult.'),
('easy', '容易的', '/ˈiːzi/', 'adjective', 2, 'The test was easy.'),
('happy', '快乐的', '/ˈhæpi/', 'emotion', 2, 'I am happy to see you.'),
('sad', '悲伤的', '/sæd/', 'emotion', 2, 'He looks sad today.'),
('angry', '生气的', '/ˈæŋɡri/', 'emotion', 2, 'She was angry at me.'),
('tired', '疲倦的', '/ˈtaɪərd/', 'emotion', 2, 'I feel tired after work.'),
('study', '学习', '/ˈstʌdi/', 'education', 2, 'I study English every day.'),
('learn', '学习', '/lɜːrn/', 'education', 2, 'I want to learn Chinese.'),
('teach', '教', '/tiːtʃ/', 'education', 2, 'She teaches mathematics.'),
('work', '工作', '/wɜːrk/', 'career', 2, 'I work in an office.'),
('business', '商业', '/ˈbɪznəs/', 'career', 2, 'He owns a business.'),
('money', '钱', '/ˈmʌni/', 'finance', 2, 'I need to save money.'),
('buy', '买', '/baɪ/', 'shopping', 2, 'I want to buy a gift.'),
('sell', '卖', '/sel/', 'shopping', 2, 'They sell fresh fruits.'),
('restaurant', '餐厅', '/ˈrestrɑːnt/', 'food', 2, 'Lets eat at a restaurant.'),
('coffee', '咖啡', '/ˈkɔːfi/', 'food', 2, 'I drink coffee every morning.'),

-- Advanced Level (difficulty 3)
('achieve', '实现', '/əˈtʃiːv/', 'verb', 3, 'I want to achieve my goals.'),
('analyze', '分析', '/ˈænəlaɪz/', 'verb', 3, 'We need to analyze the data.'),
('communicate', '交流', '/kəˈmjuːnɪkeɪt/', 'verb', 3, 'Good leaders communicate well.'),
('develop', '发展', '/dɪˈveləp/', 'verb', 3, 'We develop software.'),
('environment', '环境', '/ɪnˈvaɪrənmənt/', 'nature', 3, 'Protect the environment.'),
('experience', '经验', '/ɪkˈspɪriəns/', 'common', 3, 'She has much experience.'),
('government', '政府', '/ˈɡʌvərnmənt/', 'politics', 3, 'The government announced new policies.'),
('knowledge', '知识', '/ˈnɑːlɪdʒ/', 'education', 3, 'Knowledge is power.'),
('opportunity', '机会', '/ˌɑːpərˈtuːnəti/', 'common', 3, 'This is a great opportunity.'),
('problem', '问题', '/ˈprɑːbləm/', 'common', 3, 'We need to solve this problem.'),
('research', '研究', '/rɪˈsɜːrtʃ/', 'science', 3, 'I am doing research.'),
('technology', '技术', '/tekˈnɑːlədʒi/', 'technology', 3, 'Technology changes fast.'),
('understand', '理解', '/ˌʌndərˈstænd/', 'verb', 3, 'I understand your concern.'),
('participate', '参与', '/pɑːrˈtɪsɪpeɪt/', 'verb', 3, 'Everyone should participate.'),
('challenge', '挑战', '/ˈtʃælɪndʒ/', 'common', 3, 'This is a big challenge.'),
('culture', '文化', '/ˈkʌltʃər/', 'social', 3, 'Different countries have different cultures.'),
('education', '教育', '/ˌedʒuˈkeɪʃn/', 'education', 3, 'Education is fundamental.'),
('language', '语言', '/ˈlæŋɡwɪdʒ/', 'education', 3, 'I speak three languages.'),
('society', '社会', '/səˈsaɪəti/', 'social', 3, 'Society is changing.'),
('strategy', '策略', '/ˈstrætədʒi/', 'business', 3, 'We need a new strategy.'),

-- More common words
('love', '爱', '/lʌv/', 'emotion', 1, 'I love my parents.'),
('like', '喜欢', '/laɪk/', 'emotion', 1, 'I like ice cream.'),
('want', '想要', '/wɑːnt/', 'verb', 1, 'I want to go home.'),
('need', '需要', '/niːd/', 'verb', 1, 'I need your help.'),
('help', '帮助', '/help/', 'verb', 1, 'Can you help me?'),
('talk', '说话', '/tɔːk/', 'verb', 1, 'We need to talk.'),
('listen', '听', '/ˈlɪsn/', 'verb', 1, 'Please listen carefully.'),
('read', '读', '/riːd/', 'verb', 1, 'I read books every night.'),
('write', '写', '/raɪt/', 'verb', 1, 'Write your name here.'),
('speak', '说', '/spiːk/', 'verb', 1, 'I speak English.'),
('walk', '走', '/wɔːk/', 'verb', 1, 'Lets walk in the park.'),
('run', '跑', '/rʌn/', 'verb', 1, 'I run every morning.'),
('eat', '吃', '/iːt/', 'verb', 1, 'Lets eat dinner.'),
('drink', '喝', '/drɪŋk/', 'verb', 1, 'Drink more water.'),
('sleep', '睡觉', '/sliːp/', 'verb', 1, 'I need to sleep.'),
('play', '玩', '/pleɪ/', 'verb', 1, 'Children play games.'),
('school', '学校', '/skuːl/', 'education', 1, 'I go to school.'),
('teacher', '老师', '/ˈtiːtʃər/', 'education', 1, 'My teacher is kind.'),
('student', '学生', '/ˈstuːdnt/', 'education', 1, 'I am a student.'),
('today', '今天', '/təˈdeɪ/', 'time', 1, 'Today is Monday.'),
('tomorrow', '明天', '/təˈmɑːroʊ/', 'time', 1, 'See you tomorrow.'),
('yesterday', '昨天', '/ˈjestərdeɪ/', 'time', 1, 'I saw him yesterday.'),
('year', '年', '/jɪr/', 'time', 2, 'Happy new year!'),
('month', '月', '/mʌnθ/', 'time', 2, 'This month is busy.'),
('week', '周', '/wiːk/', 'time', 2, 'Last week was fun.'),
('hour', '小时', '/ˈaʊər/', 'time', 2, 'Wait one hour.'),
('minute', '分钟', '/ˈmɪnɪt/', 'time', 2, 'Just a minute please.'),
('weather', '天气', '/ˈweðər/', 'nature', 2, 'The weather is nice.'),
('sun', '太阳', '/sʌn/', 'nature', 1, 'The sun is shining.'),
('rain', '雨', '/reɪn/', 'nature', 1, 'Its raining today.'),
('snow', '雪', '/snoʊ/', 'nature', 2, 'I love snow.'),
('wind', '风', '/wɪnd/', 'nature', 2, 'The wind is strong.'),
('hot', '热的', '/hɑːt/', 'adjective', 1, 'Its very hot today.'),
('cold', '冷的', '/koʊld/', 'adjective', 1, 'The water is cold.'),
('big', '大的', '/bɪɡ/', 'adjective', 1, 'This is a big house.'),
('small', '小的', '/smɔːl/', 'adjective', 1, 'I have a small dog.'),
('good', '好的', '/ɡʊd/', 'adjective', 1, 'This is very good.'),
('bad', '坏的', '/bæd/', 'adjective', 1, 'Thats a bad idea.'),
('new', '新的', '/nuː/', 'adjective', 1, 'I bought new shoes.'),
('old', '旧的', '/oʊld/', 'adjective', 1, 'This is an old building.'),
('fast', '快的', '/fæst/', 'adjective', 2, 'He is a fast runner.'),
('slow', '慢的', '/sloʊ/', 'adjective', 2, 'The train is slow.'),
('strong', '强壮的', '/strɔːŋ/', 'adjective', 2, 'He is very strong.'),
('weak', '虚弱的', '/wiːk/', 'adjective', 2, 'I feel weak today.');

-- Insert achievements
INSERT INTO achievements (name, description, icon, requirement_type, requirement_value) VALUES
('First Word', 'Learn your first word', '🎯', 'words_learned', 1),
('Word Explorer', 'Learn 10 words', '🌟', 'words_learned', 10),
('Word Master', 'Learn 50 words', '🏆', 'words_learned', 50),
('Vocabulary Champion', 'Learn 100 words', '👑', 'words_learned', 100),
('3-Day Streak', 'Study for 3 consecutive days', '🔥', 'streak_days', 3),
('7-Day Streak', 'Study for 7 consecutive days', '🔥🔥', 'streak_days', 7),
('30-Day Streak', 'Study for 30 consecutive days', '🔥🔥🔥', 'streak_days', 30),
('Practice Beginner', 'Complete 10 exercises', '📝', 'exercises_completed', 10),
('Practice Expert', 'Complete 50 exercises', '📚', 'exercises_completed', 50),
('Perfect Score', 'Get 100% on an exercise', '💯', 'perfect_score', 1),
('Early Bird', 'Study before 8 AM', '🌅', 'early_study', 1),
('Night Owl', 'Study after 10 PM', '🦉', 'late_study', 1),
('Speed Learner', 'Learn 20 words in one day', '⚡', 'daily_words', 20),
('Bookmark Collector', 'Bookmark 10 words', '⭐', 'bookmarks', 10);
